import os
import re
from dotenv import load_dotenv
import pdfplumber
import numpy as np
import oracledb
import unicodedata
from dataclasses import dataclass
from typing import List, Tuple, Optional
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

load_dotenv()

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
os.environ["TOKENIZERS_PARALLELISM"] = "FALSE"


@dataclass
class Chunk:
    text: str
    source: str
    page: int
    chunk_id: int
    line_number: Optional[int] = None


class OracleVectorStore:
    def __init__(self, user, password, dsn):
        self.user = user
        self.password = password
        self.dsn = dsn
        self.table_name = "document_chunks2"
        self.dim = 384

    def get_connection(self):
        return oracledb.connect(user=self.user, password=self.password, dsn=self.dsn)

    def ensure_table_exists(self, dim: int):
        self.dim = dim
        ddl = f"""
        DECLARE
            e_table_exists EXCEPTION;
            PRAGMA EXCEPTION_INIT(e_table_exists, -955);
            column_exists NUMBER;
        BEGIN
            BEGIN
                EXECUTE IMMEDIATE '
                    CREATE TABLE {self.table_name} (
                        id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        doc_name    VARCHAR2(255),
                        page_number NUMBER,
                        line_number NUMBER,
                        text_chunk  CLOB,
                        embedding   VECTOR({dim}, FLOAT32)
                    ) TABLESPACE USERS
                ';
            EXCEPTION
                WHEN e_table_exists THEN
                    SELECT count(*) INTO column_exists FROM user_tab_cols
                    WHERE table_name = UPPER('{self.table_name}') AND column_name = 'LINE_NUMBER';

                    IF column_exists = 0 THEN
                        EXECUTE IMMEDIATE 'DROP TABLE {self.table_name} CASCADE CONSTRAINTS';
                        EXECUTE IMMEDIATE '
                            CREATE TABLE {self.table_name} (
                                id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                doc_name    VARCHAR2(255),
                                page_number NUMBER,
                                line_number NUMBER,
                                text_chunk  CLOB,
                                embedding   VECTOR({dim}, FLOAT32)
                            ) TABLESPACE USERS
                        ';
                    END IF;
            END;
        EXCEPTION
            WHEN OTHERS THEN RAISE;
        END;
        """

        idx_name = f"{self.table_name}_vidx"
        idx_ddl = f"""
        DECLARE
            e_idx_exists EXCEPTION;
            PRAGMA EXCEPTION_INIT(e_idx_exists, -955);
            e_not_supported EXCEPTION;
            PRAGMA EXCEPTION_INIT(e_not_supported, -40674);
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE VECTOR INDEX {idx_name}
                ON {self.table_name} (embedding)
                ORGANIZATION NEIGHBOR GRAPH
                DISTANCE COSINE
            ';
        EXCEPTION
            WHEN e_idx_exists THEN NULL;
            WHEN e_not_supported THEN
                DBMS_OUTPUT.PUT_LINE('Vector index not supported, skipping.');
            WHEN OTHERS THEN RAISE;
        END;
        """
        print(f"Ensuring table {self.table_name} exists in Oracle...")
        try:
            with self.get_connection() as conn:
                with conn.cursor() as cur:
                    cur.execute(ddl)
                    try:
                        cur.execute(idx_ddl)
                    except Exception as e:
                        print(f"⚠️ Warning creating index: {e}")
                conn.commit()
            print("✅ Oracle table verified.")
        except Exception as e:
            print(f"❌ Error ensuring table exists: {e}")
            raise

    def add_chunks(self, chunks: List[Chunk], embeddings: np.ndarray):
        print(f"Inserting {len(chunks)} chunks into Oracle...")
        try:
            with self.get_connection() as conn:
                with conn.cursor() as cur:
                    sql = f"INSERT INTO {self.table_name} (doc_name, page_number, line_number, text_chunk, embedding) VALUES (:1, :2, :3, :4, :5)"
                    for i, c in enumerate(chunks):
                        vec = embeddings[i].astype(np.float32).tolist()
                        vec_str = "[" + ",".join(map(str, vec)) + "]"
                        cur.execute(sql, [
                            os.path.basename(c.source),
                            c.page,
                            c.line_number or 0,
                            c.text,
                            vec_str
                        ])
                conn.commit()
            print(f"✅ Successfully inserted {len(chunks)} chunks.")
        except Exception as e:
            print(f"❌ Error inserting chunks: {e}")
            raise

    def search(self, query_embedding: np.ndarray, top_k: int = 8, doc_name: Optional[str] = None) -> List[
        Tuple[float, Chunk]]:
        q_emb_str = "[" + ",".join(map(str, query_embedding.tolist())) + "]"
        results = []
        with self.get_connection() as conn:
            with conn.cursor() as cur:
                where_clause = ""
                params = {"q_emb": q_emb_str, "k": top_k}
                if doc_name:
                    where_clause = "WHERE doc_name = :doc_name"
                    params["doc_name"] = os.path.basename(doc_name)

                sql = f"""
                SELECT
                    VECTOR_DISTANCE(embedding, :q_emb, COSINE) as score,
                    doc_name,
                    page_number,
                    line_number,
                    text_chunk
                FROM {self.table_name}
                {where_clause}
                ORDER BY score
                FETCH FIRST :k ROWS ONLY
                """
                cur.execute(sql, **params)
                for i, row in enumerate(cur.fetchall()):
                    score, doc, page, line, text_lob = row
                    text = text_lob.read() if hasattr(text_lob, 'read') else text_lob
                    results.append(
                        (1.0 - float(score), Chunk(text=text, source=doc, page=page, line_number=line, chunk_id=i)))
        return results

    def get_all_chunks(self) -> List[Chunk]:
        chunks = []
        try:
            with self.get_connection() as conn:
                with conn.cursor() as cur:
                    sql = f"SELECT id, doc_name, page_number, line_number, text_chunk FROM {self.table_name}"
                    cur.execute(sql)
                    for row in cur.fetchall():
                        chunk_id, doc, page, line, text_lob = row
                        text = text_lob.read() if hasattr(text_lob, 'read') else text_lob
                        chunks.append(Chunk(
                            text=text,
                            source=doc,
                            page=page,
                            chunk_id=chunk_id,
                            line_number=line
                        ))
        except Exception as e:
            print(f"⚠️ Eroare la extragerea chunk-urilor din DB: {e}")
        return chunks


# --- PREPROCESSING & CHUNKING ---
PAGE_NUM_PATTERNS = [
    r'^\s*\d+\s*$',
    r'^\s*page\s*\d+(\s*of\s*\d+)?\s*$',
    r'^\s*\d+\s+\d+\s*$',
]


def clean_pdf_text(text: str) -> List[Tuple[int, str]]:
    text = text.replace("\r", "\n")
    text = re.sub(r'(\w+)-\n\s*(\w+)', r'\1\2', text)
    cleaned_lines = []
    for i, line in enumerate(text.split("\n"), start=1):
        raw = line.strip()
        if not raw:
            continue
        lower = raw.lower()
        if any(re.match(pat, lower) for pat in PAGE_NUM_PATTERNS):
            continue
        if re.match(r'^[_\-–—=]{5,}$', raw):
            continue
        raw = re.sub(r'[ \t]+', ' ', raw)
        cleaned_lines.append((i, raw))
    return cleaned_lines


def load_and_clean_pdfs(pdf_paths: List[str], min_chars_per_page: int = 10) -> List[Tuple[str, int, int, str]]:
    all_lines = []
    for path in pdf_paths:
        with pdfplumber.open(path) as pdf:
            for i, page in enumerate(pdf.pages, start=1):
                text = page.extract_text(layout=True) or page.extract_text() or ""
                lines = clean_pdf_text(text)
                total_text = " ".join(l[1] for l in lines)
                if total_text and len(total_text) >= min_chars_per_page:
                    for line_num, line_text in lines:
                        all_lines.append((path, i, line_num, line_text))
    return all_lines


def split_into_chunks(
        lines: List[Tuple[str, int, int, str]],
        chunk_size: int = 900,
        overlap_chars: int = 150,
        min_chunk_chars: int = 50,
) -> List[Chunk]:
    chunks: List[Chunk] = []
    chunk_id = 0
    if not lines:
        return []

    # Grupăm liniile pe pagini și documente
    pages_map = {}
    for source, page_num, line_num, text in lines:
        key = (source, page_num)
        if key not in pages_map:
            pages_map[key] = []
        pages_map[key].append((line_num, text))

    for (source, page_num), page_lines in pages_map.items():
        buf_lines: List[Tuple[int, str]] = []

        def flush_buffer():
            nonlocal chunk_id
            if not buf_lines:
                return
            buf_text = "\n".join(l[1] for l in buf_lines).strip()
            if len(buf_text) >= min_chunk_chars:
                start_line = buf_lines[0][0]
                chunks.append(
                    Chunk(text=buf_text, source=source, page=page_num, line_number=start_line, chunk_id=chunk_id))
                chunk_id += 1

        for line_num, line_text in page_lines:
            current_buf_text = "\n".join(l[1] for l in buf_lines + [(line_num, line_text)])

            # Când depășim 900 de caractere
            if buf_lines and len(current_buf_text) > chunk_size:
                flush_buffer()  # Salvăm chunk-ul în baza de date

                tail = []
                tail_len = 0
                # Mergem de la ultima linie înapoi și adunăm text
                for l in reversed(buf_lines):
                    tail.insert(0, l)  # Adăugăm linia la începutul listei tail
                    tail_len += len(l[1]) + 1  # +1 pentru caracterul de linie nouă (\n)

                    # Ne oprim când am adunat destule caractere pentru overlap
                    if tail_len >= overlap_chars:
                        break
                # ------------------------------

                # Începem noul chunk cu coada de ~150 caractere + linia nouă
                buf_lines = tail + [(line_num, line_text)]
            else:
                buf_lines.append((line_num, line_text))

        # Salvăm ce a rămas la finalul paginii
        flush_buffer()

    # Eliminăm posibilele duplicate exacte (dacă PDF-ul are elemente repetitive)
    seen = set()
    uniq: List[Chunk] = []
    for c in chunks:
        key = (c.text, c.source, c.page, c.line_number)
        if key not in seen:
            seen.add(key)
            uniq.append(c)

    return uniq

# --- CORE RAG FUNCTIONS ---
def build_vector_store(
        chunks: List[Chunk],
        model_name: str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
):
    embedder = SentenceTransformer(model_name)
    dim = embedder.get_embedding_dimension()

    user = os.getenv("ORACLE_USER", "rag_user")
    password = os.getenv("ORACLE_PASSWORD", "rag_pass")
    dsn = os.getenv("ORACLE_DSN", "172.25.208.1:1522/FREEPDB1")

    store = OracleVectorStore(user, password, dsn)
    store.ensure_table_exists(dim)
    if chunks:
        texts = [c.text for c in chunks]
        embeddings = embedder.encode(texts, show_progress_bar=True, normalize_embeddings=True)
        embeddings = np.asarray(embeddings, dtype="float32")
        print("ℹ️ Uploading chunks to Oracle AI Vector Search.")
        store.add_chunks(chunks, embeddings)
    return store, embedder


def retrieve_context(
        question: str,
        store: OracleVectorStore,
        embedder: SentenceTransformer,
        top_k: int = 8,
        min_score: float = 0.1,
        selected_doc: Optional[str] = None
) -> List[Tuple[float, Chunk]]:
    if store is None:
        return []
    q_emb = embedder.encode([question], normalize_embeddings=True)
    q_emb = np.asarray(q_emb, dtype="float32")[0]
    results = store.search(q_emb, top_k=top_k, doc_name=selected_doc)
    return [(score, chunk) for score, chunk in results if score >= min_score]


# --- LEXICAL FALLBACK ---
def normalize_for_match(text: str) -> str:
    text = unicodedata.normalize("NFD", text.lower())
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    return re.sub(r"[^a-z0-9\s]", " ", text)


def token_roots(text: str) -> List[str]:
    normalized = normalize_for_match(text)
    tokens = re.findall(r"\w+", normalized)
    roots: List[str] = []
    for token in tokens:
        if len(token) >= 6:
            roots.append(token[:6])
        elif len(token) >= 4:
            roots.append(token[:4])
        elif len(token) >= 3:
            roots.append(token)
    return roots


GENERIC_QUERY_ROOTS = {"care", "este", "ce", "cum", "se", "the", "what", "how", "tell", "is", "are"}


def meaningful_roots(text: str) -> set[str]:
    roots = set(token_roots(text))
    filtered = {root for root in roots if root not in GENERIC_QUERY_ROOTS}
    return filtered or roots


def lexical_fallback(question: str, chunks: List[Chunk], top_k: int = 6) -> List[Tuple[float, Chunk]]:
    if not chunks:
        return []
    q = question.strip().lower()
    hits: List[Tuple[float, Chunk]] = []
    target_roots = meaningful_roots(q)
    if not target_roots:
        return []
    for c in chunks:
        t = c.text.lower()
        chunk_roots = set(token_roots(t))
        overlap = 0
        for root in target_roots:
            if root in chunk_roots:
                if len(root) >= 5:
                    overlap += 2
                else:
                    overlap += 1
        if overlap > 0:
            hits.append((overlap / 10.0, c))
    hits.sort(key=lambda x: x[0], reverse=True)
    return hits[:top_k]


# --- LLM AND CHAT FORMATTING ---
def format_citations(citations: List[str]) -> str:
    unique = list(dict.fromkeys(citations))
    return " ".join(unique[:3])


class LocalCausalQA:
    def __init__(self, model_id: str = "Qwen/Qwen2.5-1.5B-Instruct", device: str = "cpu"):
        print(f"Loading tokenizer for {model_id}...")
        self.tokenizer = AutoTokenizer.from_pretrained(model_id)

        print(f"Loading causal model for {model_id}...")
        dtype = torch.float32 if device == "cpu" else torch.float16
        self.model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=dtype,
            low_cpu_mem_usage=True
        )

        if device == "cpu":
            self.device = torch.device("cpu")
        elif device == "cuda" and torch.cuda.is_available():
            self.device = torch.device("cuda")
        elif torch.backends.mps.is_available():
            self.device = torch.device("mps")
            print("✨ Using Apple MPS (Metal) for LLM acceleration.")
        else:
            self.device = torch.device("cpu")

        print(f"Moving model to {self.device}...")
        self.model.to(self.device)
        self.model.eval()
        print("Model loaded and ready.")

    def __call__(self, prompt: str, max_new_tokens: int = 250) -> str:
        messages = [
            {"role": "system",
             "content": "You are a precise assistant. Answer strictly based on the provided context."},
            {"role": "user", "content": prompt}
        ]

        text_prompt = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        inputs = self.tokenizer(
            text_prompt,
            return_tensors="pt",
            truncation=True,
            max_length=2048
        ).to(self.device)

        try:
            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs,
                    max_new_tokens=max_new_tokens,
                    do_sample=False,
                    pad_token_id=self.tokenizer.eos_token_id
                )
        except Exception as e:
            print(f"⚠️ Eroare la generare: {e}")
            return "A apărut o eroare la generarea răspunsului."

        input_length = inputs.input_ids.shape[1]
        generated_tokens = outputs[0][input_length:]
        text = self.tokenizer.decode(generated_tokens, skip_special_tokens=True)
        return text.strip()


def setup_llm(model_id: str = "Qwen/Qwen2.5-1.5B-Instruct", device: str = "cpu"):
    return LocalCausalQA(model_id=model_id, device=device)


def answer_question(
        question: str,
        llm,
        retrieved: List[Tuple[float, Chunk]],
        max_context_chars: int = 1200,
        conversation_history=None,
) -> str:
    context_parts = []
    used = 0
    used_sources = []

    # Adunăm fragmentele recuperate, limitate de spațiul maxim
    for score, c in retrieved:
        tag = f"[{os.path.basename(c.source)} p.{c.page}]"
        piece = f"{tag}\n{c.text}\n"
        if used + len(piece) > max_context_chars:
            break
        context_parts.append(piece)
        used += len(piece)
        used_sources.append(tag)

    context = "\n---\n".join(context_parts).strip()

    not_found_msg = "The available documents do not contain an explicit answer to your question."

    prompt = (
        f"Context information is below.\n"
        f"---------------------\n"
        f"{context}\n"
        f"---------------------\n"
        f"Given the context information and not prior knowledge, answer the query.\n"
        f"If the answer is not in the context, reply exactly with: '{not_found_msg}'\n\n"
        f"Query: {question}\n"
        f"Answer:"
    )

    out = llm(prompt, max_new_tokens=200)
    print(f"LLM output: {out}")

    clean_out = out.strip().lower()
    if (not clean_out or len(clean_out) < 5 or
            not_found_msg.lower() in clean_out or
            clean_out == "n/a"):
        return not_found_msg

    citations = format_citations(used_sources)
    if citations and citations not in out:
        return f"{out.strip()} {citations}"
    return out.strip()


# --- MAIN RAG CLASS ---
class ManualRAG:
    def __init__(self):
        self.chunks: List[Chunk] = []
        self.store = None
        self.embedder = None
        self.llm = None
        self.initialized = False

    def setup(self, pdf_paths: List[str], display_name: Optional[str] = None, device: str = "cpu"):
        print(f"📄 Loading and cleaning PDFs: {pdf_paths}")
        pages = load_and_clean_pdfs(pdf_paths)
        if not pages:
            print("❌ No text extracted from PDFs.")
            return

        print("✂️ Chunking...")
        new_chunks = split_into_chunks(pages, chunk_size=900, overlap_paragraphs=1, min_chunk_chars=50)

        if display_name:
            for c in new_chunks:
                c.source = display_name

        self.chunks.extend(new_chunks)

        print("🔢 Embeddings + Oracle AI Vector Search...")
        self.store, self.embedder = build_vector_store(new_chunks)

        if not self.initialized:
            print("🧠 Loading LLM...")
            self.llm = setup_llm(device=device)
            self.initialized = True
        print(f"✅ Ready. {len(new_chunks)} chunks indexed.")

    def load_from_db(self, device: str = "cpu",
                     model_name: str = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"):
        print("🧠 Se încarcă LLM-ul...")
        self.llm = setup_llm(device=device)

        print("🔢 Se inițializează modelul de Embeddings...")
        self.embedder = SentenceTransformer(model_name)
        dim = self.embedder.get_embedding_dimension()

        user = os.getenv("ORACLE_USER", "rag-project-user")
        password = os.getenv("ORACLE_PASSWORD", "parola_rag")
        dsn = os.getenv("ORACLE_DSN", "172.25.208.1:1522/FREEPDB1")

        self.store = OracleVectorStore(user, password, dsn)
        self.store.ensure_table_exists(dim)

        print("📥 Se preiau documentele existente din Oracle...")
        self.chunks = self.store.get_all_chunks()

        self.initialized = True
        print(f"✅ Gata! Am încărcat {len(self.chunks)} fragmente existente.")

    def ask(self, question: str, top_k: int = 8, min_score: float = 0.0, max_context_chars: int = 3000,
            selected_doc: Optional[str] = None, conversation_history=None) -> str:
        if not self.initialized or not self.chunks:
            return "Please upload and process a document first."

        retrieved = retrieve_context(
            question,
            self.store,
            self.embedder,
            top_k=top_k,
            min_score=max(min_score, 0.20),
            selected_doc=selected_doc
        )

        if not retrieved:
            retrieved = lexical_fallback(question, self.chunks, top_k=min(6, top_k))

        if not retrieved:
            return "Your question is not related to the subject of the provided document."

        answer = answer_question(
            question,
            self.llm,
            retrieved,
            max_context_chars=max_context_chars,
            conversation_history=conversation_history,
        )
        return answer

    def semantic_search(self, query: str, top_k: int = 5) -> List[dict]:
        if not self.initialized or not self.store:
            return []

        retrieved = retrieve_context(query, self.store, self.embedder, top_k=top_k, min_score=0.15)

        if not retrieved:
            retrieved = lexical_fallback(query, self.chunks, top_k=top_k)

        results = []
        for score, chunk in retrieved:
            results.append({
                "doc_name": os.path.basename(chunk.source),
                "score": score,
                "page": chunk.page,
                "text": chunk.text
            })

        return results